<?php
//引用此页面前需先引用conf.php
error_reporting(E_ALL ^ E_DEPRECATED);
LIB('db');

class AuthManager extends DBManager{
    public function info()
    {
		//return self::GenerateOrUpdateAuthToken('12332');
        return "AuthManager"; // TODO: Change the autogenerated stub
    }

	public function AuthManager(){
		
	}
	
	public static function GenerateOrUpdateAuthToken($uid){
		$AM = new AuthManager();
		$secret = rand(100000,999999);
		$timeStamp = PRC_TIME();
		$result = $AM->UpdateDataToTableByQuery($AM->TName('tAuth'),['secret'=>$secret,'time'=>$timeStamp],self::FieldIsValue('uid',$uid));
		if(!$result){
			$AM->InsertDataToTable($AM->TName('tAuth'),['uid'=>$uid,'secret'=>$secret,'time'=>$timeStamp]);
		}
		return ['secret'=>$secret,'timeStamp'=>$timeStamp];
	}
	
	public static function ConfirmRequest($module,$action,$requestArray){//requestArray不包含module=>action的对照关系
		if(!isset($requestArray['signal']) || !isset($requestArray['openid'])){
			return ["result":false,"content":"签名错误"];
		}
		$signal = $requestArray['signal'];
		unset($requestArray['signal']);
		if($signal == json_encode($requestArray));
		return ["result":true];
	}
	
}
?>