<?php
//引用此页面前需先引用conf.php
error_reporting(E_ALL ^ E_DEPRECATED);


class SnippetManager extends Manager{
    public function info()
    {
        return "SnippetManager"; // TODO: Change the autogenerated stub
    }
	
	public $config = [
		'viewPath'=>'../TinydreamWeb/view'
	];

	public function SnippetManager(){
		
	}
	
	public function BuildSnippets($datas){
		$path = $this->config['viewPath'];
		if(isset($_REQUEST['url'])){
			$path=$_REQUEST['url'];
		}
		$result = [];
		$datas = json_decode($datas,true);
		foreach($datas as $data){
			$result[$data['name']] = $this->SingleSnippet($path,$data['name'],json_encode($data['data']));
		}
		$backMsg = RESPONDINSTANCE('0');
		$backMsg['snippet']=$result;
		return $backMsg;
	}
	
	public function SingleSnippet($path,$name,$data){
		$fullPath = $path.'/'.$name;
		$endfix = substr($fullPath,strrpos($fullPath,'.')+1);
		if($endfix != 'html'){
			$fullPath = $fullPath.'.html';
		}
		$data = json_decode($data,true);
		$template = file_get_contents($fullPath);
		$result = '';
		foreach($data as $seek=>$index){
			$current = $template;
			foreach($index as $key=>$value){
				$current = str_replace("{{{$key}}}",$value,$current);
			}
			$result = $result.$current;
		}
		$result = str_replace("<","#LB#",$result);
		$result = str_replace(">","#RB#",$result);
		return $result;
	}
	
	public function BuildSnippet($name,$data){
		$path = $this->config['viewPath'];
		if(isset($_REQUEST['url'])){
			$path=$_REQUEST['url'];
		}
		$backMsg = RESPONDINSTANCE('0');
		$backMsg['snippet'][$name]=$this->SingleSnippet($path,$name,$data);
		return $backMsg;
	}
}
?>