<?php
//引用此页面前需先引用conf.php
error_reporting(E_ALL ^ E_DEPRECATED);
LIB("ds");
LIB("no");//通知
LIB("us");//用户
class RedPackManage extends Manager{
    public static function GenerateRedPackageID(){
        return "1111123447465765757653";
    }
    //生成领取红包时的订单号
    public static function GenerateRedPackageOrderID(){
        return "1111123447465765757653";
    }
    //获取红包的领取信息
    public static function GenerateRedPackageRecInfo($rid){
        return [
            "rpid"=>"",
            "index"=>0,
        ];
    }
    public function info()
    {
        return "RedPackManage"; // TODO: Change the autogenerated stub
    }

    //发红包统一下单准备支付
    public function CreateRedPackae($pid,$rcount,$content,$bill,$uid){
        //前提条件的判断
        //用户绑定手机号
            //未绑定，返回需绑定
        //梦想互助期号是否存在，未完成互助
            //梦想互助失效，返回失败
        //rcount小于200，
            //rcount大于300，返回错误
        //删除用户有PAYMENT的订单
        $rid = self::GenerateRedPackageID();
        $gcount = 0;
        $acount = 0;
        $rtype = "STANDARD";
        $ctime = PRC_TIME();
        $ptime = 0;
        $state = "PAYMENT";


        //统一下单 crp
        $DSM = new DreamServersManager();
        $orderInfo = $DSM->WxPayWeb($rid,$bill,$uid);
        if($orderInfo['code'] != "0"){
            //统一下单错误
//            return RESPONDINSTANCE('');
        }else{
            //插入红包信息进入数据库，redpackorder数据表
        }
        $backMsg = RESPONDINSTANCE('0');
        $backMsg['order'] = $orderInfo;
        return $backMsg;
    }
    //红包支付创建成功 cprs
    public function CreateRedPackSuccess($uid,$rid){
        //判断用户是否创建了该红包
            //用户不拥有该红包，为错误
        //订单状态修改为RUNNINNG
        //ptime修改为当前时间
        $backMsg = RESPONDINSTANCE('0');
        return $backMsg;
    }
    //获取红包信息,打开领取红包页面 grp
    public function GetRedPack($rid){
        //从rid获取红包信息，
        $backMsg = RESPONDINSTANCE('0');
        return $backMsg;
    }
    //获取用户红包列表,红包记录页面（发出）gurps
    public function GetUserRedPacksSend($uid,$seek,$count){
        //通过uid获取用户发出的红包信息
        $backMsg = RESPONDINSTANCE('0');
        return $backMsg;
    }
    //获取用户红包列表,红包记录页面（收到）gurpr
    public function GetUserRedPacksRecive($uid,$seek,$count){
        //通过uid获取用户收到的红包信息
        $backMsg = RESPONDINSTANCE('0');
        return $backMsg;
    }
    //领取红包 orp
	public function OpenRedPack($uid,$rid){
        //判断用户当日购买份数是否到达5次
        //判断红包是否有效，红包存在未领取份数，对应的梦想互助未结束
        //获取红包信息
        //用户当日购买份数+1
        //判断用户是否绑定手机号
        //判断用户是否提交过梦想
        //生成红包购买订单
        //创建编号
        //红包订单已领份数+1
        //生成红包领取记录
        //发送通知给用户
        $backMsg = RESPONDINSTANCE('0');
        return $backMsg;
    }
	public function RedPackManag(){


    }
}
?>