<?php
//引用此页面前需先引用conf.php
error_reporting(E_ALL ^ E_DEPRECATED);


class RedPackManage extends Manager{
    public function info()
    {
        return "RedPackManage"; // TODO: Change the autogenerated stub
    }

	public function RedPackManage(){
		
	}
}
?>