<?php
//引用此页面前需先引用conf.php
error_reporting(E_ALL ^ E_DEPRECATED);

LIB('db');
LIB('dp');
define("DEFAULT_PAGE_SIZE",5);
define("DEFAULT_START_SEEK",0);
class BackgroundController extends DBManager {
    public $pages = [
        'postDream'=>['id'=>'post','title'=>'发布梦想池','path'=>'admin/postdream.php'],
        'verify'=>['id'=>'verf','title'=>'审核','path'=>'admin/verify.php'],
        'navi'=>['id'=>'nav','title'=>'导航栏','path'=>'admin/navagator.php'],
    ];
    public function info()
    {
        return "BackgroundController"; // TODO: Change the autogenerated stub
    }


    public function BuildNavigator(){
        $pageData = $this->pages['navi'];
        require ($pageData['path']);
    }


    //引用发布梦想池
    public function BuildPostDream(){
        $pageData = $this->pages['postDream'];
        $DPM = new DreamPoolManager();
        $pageData['count'] = $DPM->CountPools()['count'];
        $pageData['psize'] = (isset($_REQUEST['psize']))?$_REQUEST['psize']:DEFAULT_PAGE_SIZE;
        $pageData['seek'] = (isset($_REQUEST['seek']))?$_REQUEST['seek']:DEFAULT_START_SEEK;

        $pageData['pages'] = ceil($pageData['count']/$pageData['psize']);
        $pageData['pools'] = $DPM->ListPoolsByRange($pageData['seek'],$pageData['psize'])['Pools'];//DBResultToArray($this->SelectDataFromTable($this->TName('tPool'),[]));
        require ($pageData['path']);
    }

    public function BuildVerify(){
        $pageData = $this->pages['verify'];
        require ($pageData['path']);
    }

	public function BackgroundController(){
		
	}
}
?>