<?php
//引用此页面前需先引用conf.php
error_reporting(E_ALL ^ E_DEPRECATED);

LIB('db');

class DreamPoolManager extends DBManager{
    public function info()
    {
        return "梦想池模块"; // TODO: Change the autogenerated stub
    }
    public function DreamPoolManager(){
        parent::__construct();
    }
}
?>