<?php
//引用此页面前需先引用conf.php
error_reporting(E_ALL ^ E_DEPRECATED);

LIB('db');
LIB('dp');
LIB('ds');

class UserManager extends DBManager{
    public static function UserExist($uid){
        $USM = new UserManager();
        return (!DBResultExist($USM->SelectDataFromTable($USM->TName('tUser'),
            [
                'uid'=>$uid,
                '_logic'=>' '
            ]
        )));
    }

    public static function UpdateUserOrderInfo($uid,$totalJoin,$pieces){
        $USM = new UserManager();
        $condition = [
            'uid'=>$uid,
            '_logic' => ' '
        ];

        $USM->UpdateDataToTable($USM->TName('tUser'),
            ['totalJoin'=>$totalJoin,'dayBuy'=>['field'=>'dayBuy','operator'=>'+','value'=>$pieces],'ltime'=>PRC_TIME()],
            $condition);
    }

    //当开奖时用户中奖调用,reward为中奖金额
    public static function OnUserReward($uid,$reward){
        $USM = new UserManager();
        $reward = $reward/100;//除100
        $USM->UpdateDataToTable($USM->TName('tUser'),
            ['totalReward'=>['field'=>'totalReward','operator'=>'+','value'=>$reward]],
            ['uid'=>$uid,'_logic'=>' ']
        );
    }

    //检查用户每日购买数量,过日后自动清0
    public static function CheckDayBoughtLimit($uid){
		$USM = new UserManager();
       
	   $condition = [
            'uid'=>$uid,
            '_logic' => ' '
        ];

        $result = DBResultToArray($USM->SelectDataFromTable($USM->TName('tUser'),$condition),true);
		
		if(empty($result[0])){
			return false;
		}
		
		$lDAY = DAY($result[0]['ltime']);
		
		$cDAY = DAY(PRC_TIME());
		
		if($cDAY > $lDAY){
			$USM->UpdateDataToTable($USM->TName('tUser'),
            ['dayBuy'=>0],
            $condition);
			$result[0]['dayBuy'] = 0;
		}

		return 5-($result[0]['dayBuy']);
    }

    //检查身份
    public static function CheckIdentity($uid,$identity){
        $USM = new UserManager();
        if(!DBResultExist($USM->SelectDataFromTable($USM->TName('tUser'),
            [
                'uid'=>$uid,
                'identity'=>$identity,
                '_logic'=>'AND'
            ]
        ))){
            return RESPONDINSTANCE('8');
        }
        return RESPONDINSTANCE('0');
    }

    //检查用户是否绑定手机
    public static function IdentifyTeleUser($uid){
        $USM = new UserManager();

        $seleResult = $USM->SelectDataFromTable($USM->TName('tUser'),
            [
                'uid'=>$uid,
                '_logic'=>' '
            ]);

        $resultArray = DBResultToArray($seleResult,true);

        if(DBResultArrayExist($resultArray)){
            $resultArray = $resultArray[0];
        }else{
            return false;
        }

        return !empty($resultArray['tele']);
    }

    //检查用户是否提交实名认证
    public static function IdentifyRealNameUser($uid,$state="SUBMIT"){
        $USM = new UserManager();

        $seleResult = $USM->SelectDataFromTable($USM->TName('tId'),
            [
                'uid'=>$uid,
                '_logic'=>' '
            ]);

        $resultArray = DBResultToArray($seleResult,true);

        if(DBResultArrayExist($resultArray)){
            $resultArray = $resultArray[0];
        }else{
            return false;
        }
        return
            ($state == "SUBMIT" &&
                ($resultArray['state']=="SUBMIT" ||
                    $resultArray['state']=="SUCCESS")) ||
            ($state == "SUCCESS" &&
                ($resultArray['state']=="SUCCESS"));
    }


    public function info()
    {
        return "用户管理器"; // TODO: Change the autogenerated stub
    }

    public function UserManager(){
		parent::__construct();
	}
	
	public function test(){
		return UserManager::CheckDayBoughtLimit("a01");
	}

    //微信登录返回用户openid,昵称,头像地址后调用 进入小程序验证身份
	public function EnterApp($uid,$nickname,$headicon){
        $condition = [
            'uid'=>$uid,
            '_logic'=>' '
        ];
        $seleResult = $this->SelectDataFromTable($this->TName('tUser'),
            $condition);
        $userArray = DBResultToArray($seleResult,true);
        $backMsg = RESPONDINSTANCE('0');
        if(empty($userArray)){//未注册
            $userArray = [
                "uid"=>$uid,
                "nickname"=>$nickname,
                "headicon"=>$headicon,
                "tele"=>"",
                "totalReward"=>0,
                "totalJoin"=>0,
                "dayBuy"=>0,
                "identity"=>"USER",
                "ltime"=>0,
            ];
            $insResult = $this->InsertDataToTable($this->TName('tUser'),$userArray);
            if(!$insResult){
                return RESPONDINSTANCE('9');
            }else{
                $backMsg['description'] = '注册成功';
            }
            //注册
        }else{//已经注册
            $userArray = $userArray[0];
            //检查更新信息
            $updateList = [];
            if($userArray['nickname'] != $nickname){
                $updateList['nickname'] = $nickname;
            }
            if($userArray['headicon'] != $headicon){
                $updateList['headicon'] = $headicon;
            }

            if(!empty($updateList)){
                $updateResult = $this->UpdateDataToTable($this->TName('tUser'),$updateList,$condition);
                if(!$updateResult){
                    return RESPONDINSTANCE('10');
                }else{
                    $backMsg['description'] = '信息更新,登录成功';
                }
            }else{
                $backMsg['description'] = '登录成功';
            }
        }

        unset($userArray['nickname']);

        unset($userArray['headicon']);

        $backMsg['selfinfo'] = $userArray;//个人基本信息
        $backMsg['buyinfo'] = DreamServersManager::GetMainOrders();//购买滚动栏
        $backMsg['mainpool'] = DreamPoolManager::GetMainPool();//在主页显示的梦想池信息
        return $backMsg;
    }

    //开始实名认证
    public function RealNameIdentifyStart($uid){
        //未实现

    }

    //实名认证成功
    public function RealNameIdentifyFinished($uid,$ccardfurl,$icardfurl,$icardburl,$ccardnum,$icardnum){
        //未实现

    }

    //实名认证审核
    public function RealNameAudit($uid,$state){
        //未实现

    }

    //显示所有需要认证信息
    public function ViewAllVerifyInfo(){
        //未实现

        //有中标梦想并提交了实名认证的用户在此查询并获取

        //提交了实名认证但无中标梦想的用户的实名认证不在此显示
    }
}
?>