<?php
//引用此页面前需先引用conf.php
error_reporting(E_ALL ^ E_DEPRECATED);

LIB('db');

class UserManager extends DBManager{

    public function info()
    {
        return "用户管理器"; // TODO: Change the autogenerated stub
    }

    public function UserManager(){
		parent::__construct();
	}
}
?>