<?php
//引用此页面前需先引用conf.php
error_reporting(E_ALL ^ E_DEPRECATED);
LIB('dp');
LIB('view');

class TradeManager extends DBManager {
    public function info()
    {
        return "TradeManager".self::GenerateTradeID(); // TODO: Change the autogenerated stub
    }

    //生成小生意id号
    public static function GenerateTradeID(){
        $DRM = new DreamManager();
        return 'TR'.(1000000000 + $DRM->CountTableRow($DRM->TName('tTrade')));
    }

	public function TradeManager(){

	}

    //通过条件字符串批量获取小生意
    public static function GetDreamsByConditionStr($tidStr){
        $TM = new TradeManager();
        $trades = DBResultToArray($TM->SelectDatasFromTable($TM->TName('tTrade'),['tid'=>$tidStr]));
        return $trades;
    }

    public function GetTradeByPid($pid){
        return self::GetTradeInfoByPid($pid);
    }
    public function GetTradeByTid($tid){
        return self::GetTradeInfoByTid($tid);
    }

	public static function GetTradeInfoByPid($pid){
        $TM = new TradeManager();
        $result = DBResultToArray(
            $TM->SelectDataByQuery($TM->TName('tTrade'),
            self::FieldIsValue('pid',$pid)
            ),true
        );
        if(!empty($result)){
            $result = $result[0];
            $result['bannerUrl'] = SnippetManager::GetAttributeFromData($result['url'],"bannerImgUrl");
            $result['awardTitle'] = SnippetManager::GetAttributeFromData($result['url'],"awardTitle");
        }
        return $result;
    }

    public static function GetTradeInfoByTid($tid){
        $TM = new TradeManager();
        $result = DBResultToArray(
            $TM->SelectDataByQuery($TM->TName('tTrade'),
                self::FieldIsValue('tid',$tid)
            ),true
        );
        if(!empty($result)){
            $result = $result[0];
            $result['bannerUrl'] = SnippetManager::GetAttributeFromData($result['url'],"bannerImgUrl");
            $result['awardTitle'] = SnippetManager::GetAttributeFromData($result['url'],"awardTitle");
        }
        return $result;
    }

    public static function GetTradeProfitPercent($uid,$pid,$lucky = false){
        $TM = new TradeManager();
        $result = DBResultToArray($TM->SelectDataByQuery($TM->TName('tOrder'),
            self::C_And(
                self::FieldIsValue('uid',$uid),
                self::FieldIsValue('pid',$pid)
            ),
            false,
            "SUM(`bill`)"
        ),false);
        echo json_encode($result);
    }

    public function GetTradePPer($uid,$pid){
        return self::GetTradeProfitPercent($uid,$pid);
    }

	//增加小生意信息
	public function AddTradeInfo($title,$url,$profit){
        $tid = self::GenerateTradeID();//生成生意ID
        $pid = DreamPoolManager::GeneratePoolIDAuto();
        $this->InsertDataToTable($this->TName('tTrade'),
            [
                'tid'=>$tid,
                'pid'=>$pid,
                'title'=>$title,
                'url'=>$url,
                'profit'=>$profit
            ]
        );
        DreamPoolManager::AddTradePool($pid,$profit);
        return RESPONDINSTANCE('0');
    }

}
?>