<?php
//引用此页面前需先引用conf.php
error_reporting(E_ALL ^ E_DEPRECATED);

LIB('db');

class AwardManager extends DBManager{

    public function info()
    {
        return "开奖模块"; // TODO: Change the autogenerated stub
    }
	public function AwardManager(){
		parent::__construct();
	}
}
?>