<?php
//引用此页面前需先引用conf.php
error_reporting(E_ALL ^ E_DEPRECATED);
LIB('db');
LIB('ds');
LIB('dp');
LIB('dr');

class AwardManager extends DBManager{

    public function info()
    {
        echo json_encode(self::DrawTheWinnerLottery(),JSON_UNESCAPED_UNICODE);
        //echo  json_encode($this->GetLottoryInfo('p01-10000001'));
        return "开奖模块"; // TODO: Change the autogenerated stub
    }

    //获取用户在某参与梦想池的编号数量
    public static function GetUserLottery($pid,$uid){
        $sql = 'SELECT COUNT(*) FROM `lottery` WHERE `uid`="'.$uid.'" AND `pid`="'.$pid.'"';
        return mysql_fetch_array(mysql_query($sql))[0];
    }

    //开奖
    public static function DrawTheWinnerLottery(){
        $data = json_decode(file_get_contents("http://f.apiplus.net/ssq.json"),true)['data'];

        if(empty($data)){
            return RESPONDINSTANCE('22');
        }

        $data = $data[0];
        $result =[];

        //foreach ($data as $value){
            $codes = explode(',',$data['opencode']);
            $tcode = '';
            if(substr( $codes[0] , 0, 1 ) == '0') {
                $codes[0] = str_replace(array("0"), "", $codes[0]);
            }
            for($i=0;$i<5;$i++){
                $tcode = $tcode.$codes[$i];
            }

            $result[$data['expect'].'期']['num'] = $data['expect'] + $tcode;
            $result[$data['expect'].'期']['expect'] = $data['expect'];
            $result[$data['expect'].'期']['code'] = $tcode;

            $AW = new AwardManager();

            if(DBResultExist($AW->SelectDataFromTable($AW->TName('tAward'),['expect'=>$data['expect'],'code'=> $tcode,'_logic'=>'OR']))){
                return RESPONDINSTANCE('23',$data['expect']);//该期双色球已开奖
            }

            $backMsg = RESPONDINSTANCE('0');
            $result[$data['expect'].'期']['target'] = $AW->DoneAlottery( $result[$data['expect'].'期']['num'],$data['expect'],$tcode);
            $backMsg['info'] = $result;
        //}
        return $backMsg;
    }

	public function AwardManager(){
		parent::__construct();
	}

	public static function GenerateLotteryID($pid,$index){
        return ($pid.'-'.(10000000+$index));
    }

	//支付后生成的中奖号
	public static function PayOrderAndCreateLottery($pid,$uid,$did,$oid,$startIndex,$endIndex){
        $AWM = new AwardManager();
        $Numbers = [];

        for($i=$startIndex;$i<$endIndex;$i++) {
            $lid = self::GenerateLotteryID($pid,$i);
            $awardArray = [
                "lid" => $lid,
                "pid" => $pid,
                "uid" => $uid,
                "index" => $i,
                "oid" => $oid,
                "did" => $did,
                'state'=>'DOING'
            ];
            if($AWM->InsertDataToTable($AWM->TName('tLottery'),$awardArray)){
                $Numbers[$lid] = $awardArray;
            }
        }
        return $Numbers;
    }

    //通过id获取开奖编号信息
    public function GetLottoryInfo($lotteryId){
        $result = DBResultToArray($this->SelectDataFromTable($this->TName('tLottery'),['lid'=>$lotteryId,'_logic'=>' ']),true,false);
        if(empty($result)){
            return $result;
        }else{
            return $result[0];
        }
    }

    //梦想池开奖
    public function DoneAlottery($DoalBallNum,$expect,$code){

        $result = DreamPoolManager::UpdateAllPools();//更新所有梦想池的状态
        $backMsg = RESPONDINSTANCE('0');

        $resultArray = [];
        $count = 0;
        $time = PRC_TIME();
        foreach ($result as $key => $item) {
            if($item['state'] == 'FINISHED'){
                if($item['info']['pcount'] <=0){
                    $cResult = "未中奖";
                }else {
                    $cResult = $key . '-' . (10000000+ (($DoalBallNum+$item['info']['pid'] ) % $item['info']['pcount']));

                    $targetLottery = $this->GetLottoryInfo($cResult);
                    if(empty($targetLottery)){
                        $cResult = "没有编号:".$cResult;
                        $backMsg['DonePools'][$key] = $cResult;
                        continue;
                    }

                    DreamManager::OnDreamDoing($targetLottery['did']);//梦想实现
                    UserManager::OnUserReward($targetLottery['uid'],$item['info']['cbill']);//用户中奖总额修改

                    $resultArray[$count][0] = $item['info']['pid'];//梦想池id
                    $resultArray[$count][1] = $targetLottery['uid'];//中奖用户id
                    $resultArray[$count][2] = $targetLottery['lid'];//开奖编号
                    $resultArray[$count][3] = $expect;//期号
                    $resultArray[$count][4] = $code;//球号
                    $resultArray[$count][5] = $targetLottery['index'];//梦想编号
                    $resultArray[$count][6] = $time;//开奖时间
                    $resultArray[$count][7] = $targetLottery['did'];//中奖梦想id
                    $resultArray[$count][8] = $item['info']['cbill'];//金额
                }
                $backMsg['DonePools'][$key] = $cResult;
                $count++;
            }
        }

        /*for($i=0;$i<$pCount;$i++){
            $resultArray[$i][0] = sha1("ghosteum_".$password."_".(1000000+$i));
            $resultArray[$i][1] = "player".($i+1);
            $resultArray[$i][2] = "null";
            $resultArray[$i][3] = "0.0.0.0";
            $resultArray[$i][4] = "NONE";
            $resultArray[$i][5] = floor($i/($pCount/$fCount));
        }*/

        if(empty($resultArray)){
            $this->InsertDataToTable($this->TName('tAward'),
                [
                    "pid"=>DAY($time),
                    "uid"=>'无开奖',
                    "lid"=>'无开奖',
                    "expect"=>$expect,
                    "code"=>$code,
                    "index"=>0,
                    "atime"=>PRC_TIME(),
                    "did"=>'无开奖',
                    "abill"=>0
                ]);
        }else {
            $this->InsertDatasToTable($this->TName('tAward'),
                [
                    "key" => ["pid", "uid", "lid", "expect", "code", "index", "atime", "did", "abill"],
                    "values" => $resultArray
                ]);
        }
        if(!isset($backMsg['DonePools'])){
            $backMsg['DonePools'] = '无符合条件梦想池';
        }

        return $backMsg;
    }

    //获取订单的抽奖号
    public function GetLotteryByOrder($oid){
        $sResult = $this->SelectDataFromTable($this->TName('tLottery'),['oid'=>$oid,'_logic'=>' ']);
        $orderArray = DBResultToArray($sResult,true);
        if(!empty($orderArray)){
            $orderArray = $orderArray;
        }
        $backMsg = RESPONDINSTANCE('0');
        $backMsg['nums'] = $orderArray;
        return $backMsg;
    }
}
?>